-- Drop existing table if needed (be careful with data loss, but for setup it's fine)
drop table if exists admins;

-- Create admins table with plain text password
create table admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null, -- Plain text password
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table admins enable row level security;

-- Insert initial admin user (password: 12345)
insert into admins (username, password) values 
('admin', '12345');
