-- Создание таблицы промокодов
CREATE TABLE IF NOT EXISTS public.promo_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code text NOT NULL,
    discount_percent integer NULL,
    discount_amount numeric(10, 2) NULL,
    min_order_amount numeric(10, 2) NULL DEFAULT 0,
    max_uses integer NULL,
    current_uses integer NULL DEFAULT 0,
    valid_from timestamp with time zone NULL DEFAULT now(),
    valid_until timestamp with time zone NULL,
    is_active boolean NULL DEFAULT true,
    created_at timestamp with time zone NULL DEFAULT now(),
    CONSTRAINT promo_codes_pkey PRIMARY KEY (id),
    CONSTRAINT promo_codes_code_key UNIQUE (code)
) TABLESPACE pg_default;

-- Enable RLS
ALTER TABLE promo_codes ENABLE ROW LEVEL SECURITY;

-- Policies for promo codes
CREATE POLICY "Public can view active promo codes"
    ON promo_codes FOR SELECT
    USING (true);

CREATE POLICY "Public can insert promo codes"
    ON promo_codes FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Public can update promo codes"
    ON promo_codes FOR UPDATE
    USING (true);

CREATE POLICY "Public can delete promo codes"
    ON promo_codes FOR DELETE
    USING (true);

-- Комментарии к полям
COMMENT ON COLUMN promo_codes.code IS 'Код промокода (уникальный)';
COMMENT ON COLUMN promo_codes.discount_percent IS 'Скидка в процентах (если используется процентная скидка)';
COMMENT ON COLUMN promo_codes.discount_amount IS 'Скидка фиксированной суммой (если используется фиксированная скидка)';
COMMENT ON COLUMN promo_codes.min_order_amount IS 'Минимальная сумма заказа для применения промокода';
COMMENT ON COLUMN promo_codes.max_uses IS 'Максимальное количество использований (NULL = неограниченно)';
COMMENT ON COLUMN promo_codes.current_uses IS 'Текущее количество использований';
COMMENT ON COLUMN promo_codes.valid_from IS 'Дата начала действия промокода';
COMMENT ON COLUMN promo_codes.valid_until IS 'Дата окончания действия промокода (NULL = бессрочно)';
COMMENT ON COLUMN promo_codes.is_active IS 'Активен ли промокод';
