-- Create products table
create table products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  image_url text, -- Main image
  images text[], -- Array of image URLs for gallery
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create orders table
create table orders (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text,
  customer_city text,
  nova_poshta_branch text,
  instagram_nick text,
  visited_psychologist boolean default false,
  total_amount numeric not null,
  status text default 'pending', -- pending, shipped, delivered, cancelled
  tracking_number text -- could be same as id or separate
);

-- Create order_items table
create table order_items (
  id bigint generated by default as identity primary key,
  order_id text references orders(id) on delete cascade not null,
  product_id bigint references products(id) not null,
  quantity int not null,
  price numeric not null -- Store price at time of purchase
);

-- Enable RLS
alter table products enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

-- Policies
-- Products: Everyone can view
create policy "Public products are viewable by everyone"
  on products for select
  using ( true );

-- Products: Everyone can insert
create policy "Public can insert products"
  on products for insert
  with check ( true );

-- Products: Everyone can update
create policy "Public can update products"
  on products for update
  using ( true );

-- Orders: Public policies
create policy "Public can create orders"
  on orders for insert
  with check ( true );

create policy "Public can view orders"
  on orders for select
  using ( true );

create policy "Public can update orders"
  on orders for update
  using ( true );

create policy "Public can delete orders"
  on orders for delete
  using ( true );

-- Order Items: Public can insert
create policy "Public can create order items"
  on order_items for insert
  with check ( true );

-- Insert some dummy data
insert into products (title, description, price, image_url, images) values
('The Great Gatsby', 'A classic novel of the Jazz Age.', 15.99, 'https://covers.openlibrary.org/b/id/7222246-L.jpg', ARRAY['https://covers.openlibrary.org/b/id/7222246-L.jpg', 'https://covers.openlibrary.org/b/id/7222246-M.jpg']),
('1984', 'A dystopian social science fiction novel and cautionary tale.', 12.50, 'https://covers.openlibrary.org/b/id/7222247-L.jpg', ARRAY['https://covers.openlibrary.org/b/id/7222247-L.jpg']),
('To Kill a Mockingbird', 'A novel by Harper Lee published in 1960.', 18.00, 'https://covers.openlibrary.org/b/id/8225266-L.jpg', ARRAY['https://covers.openlibrary.org/b/id/8225266-L.jpg']);

-- Create admins table
create table admins (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table admins enable row level security;
